//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleMapPNG
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int AddressID { get; set; }
        public int AddressTVItemID { get; set; }
        public int AddressType { get; set; }
        public int CountryTVItemID { get; set; }
        public int ProvinceTVItemID { get; set; }
        public int MunicipalityTVItemID { get; set; }
        public string StreetName { get; set; }
        public string StreetNumber { get; set; }
        public Nullable<int> StreetType { get; set; }
        public string PostalCode { get; set; }
        public string GoogleAddressText { get; set; }
        public System.DateTime LastUpdateDate_UTC { get; set; }
        public int LastUpdateContactTVItemID { get; set; }
    
        public virtual TVItem TVItem { get; set; }
        public virtual TVItem TVItem1 { get; set; }
        public virtual TVItem TVItem2 { get; set; }
        public virtual TVItem TVItem3 { get; set; }
    }
}
