//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleMapPNG
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppErrLog
    {
        public int AppErrLogID { get; set; }
        public string Tag { get; set; }
        public int LineNumber { get; set; }
        public string Source { get; set; }
        public string Message { get; set; }
        public System.DateTime DateTime_UTC { get; set; }
        public System.DateTime LastUpdateDate_UTC { get; set; }
        public int LastUpdateContactTVItemID { get; set; }
    }
}
