//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleMapPNG
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppTaskLanguage
    {
        public int AppTaskLanguageID { get; set; }
        public int AppTaskID { get; set; }
        public int Language { get; set; }
        public string StatusText { get; set; }
        public string ErrorText { get; set; }
        public int TranslationStatus { get; set; }
        public System.DateTime LastUpdateDate_UTC { get; set; }
        public int LastUpdateContactTVItemID { get; set; }
    
        public virtual AppTask AppTask { get; set; }
    }
}
