//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleMapPNG
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoxModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BoxModel()
        {
            this.BoxModelLanguages = new HashSet<BoxModelLanguage>();
            this.BoxModelResults = new HashSet<BoxModelResult>();
        }
    
        public int BoxModelID { get; set; }
        public int InfrastructureTVItemID { get; set; }
        public double Flow_m3_day { get; set; }
        public double Depth_m { get; set; }
        public double Temperature_C { get; set; }
        public int Dilution { get; set; }
        public double DecayRate_per_day { get; set; }
        public int FCUntreated_MPN_100ml { get; set; }
        public int FCPreDisinfection_MPN_100ml { get; set; }
        public int Concentration_MPN_100ml { get; set; }
        public double T90_hour { get; set; }
        public double FlowDuration_hour { get; set; }
        public System.DateTime LastUpdateDate_UTC { get; set; }
        public int LastUpdateContactTVItemID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BoxModelLanguage> BoxModelLanguages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BoxModelResult> BoxModelResults { get; set; }
        public virtual TVItem TVItem { get; set; }
    }
}
