//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleMapPNG
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoxModelResult
    {
        public int BoxModelResultID { get; set; }
        public int BoxModelID { get; set; }
        public int BoxModelResultType { get; set; }
        public double Volume_m3 { get; set; }
        public double Surface_m2 { get; set; }
        public double Radius_m { get; set; }
        public double LeftSideDiameterLineAngle_deg { get; set; }
        public double CircleCenterLatitude { get; set; }
        public double CircleCenterLongitude { get; set; }
        public bool FixLength { get; set; }
        public bool FixWidth { get; set; }
        public double RectLength_m { get; set; }
        public double RectWidth_m { get; set; }
        public double LeftSideLineAngle_deg { get; set; }
        public double LeftSideLineStartLatitude { get; set; }
        public double LeftSideLineStartLongitude { get; set; }
        public System.DateTime LastUpdateDate_UTC { get; set; }
        public int LastUpdateContactTVItemID { get; set; }
    
        public virtual BoxModel BoxModel { get; set; }
    }
}
