//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleMapPNG
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClimateSite
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClimateSite()
        {
            this.ClimateDataValues = new HashSet<ClimateDataValue>();
        }
    
        public int ClimateSiteID { get; set; }
        public int ClimateSiteTVItemID { get; set; }
        public int ECDBID { get; set; }
        public string ClimateSiteName { get; set; }
        public string Province { get; set; }
        public Nullable<double> Elevation_m { get; set; }
        public string ClimateID { get; set; }
        public Nullable<int> WMOID { get; set; }
        public string TCID { get; set; }
        public Nullable<bool> IsProvincial { get; set; }
        public string ProvSiteID { get; set; }
        public Nullable<double> TimeOffset_hour { get; set; }
        public string File_desc { get; set; }
        public Nullable<System.DateTime> HourlyStartDate_Local { get; set; }
        public Nullable<System.DateTime> HourlyEndDate_Local { get; set; }
        public Nullable<bool> HourlyNow { get; set; }
        public Nullable<System.DateTime> DailyStartDate_Local { get; set; }
        public Nullable<System.DateTime> DailyEndDate_Local { get; set; }
        public Nullable<bool> DailyNow { get; set; }
        public Nullable<System.DateTime> MonthlyStartDate_Local { get; set; }
        public Nullable<System.DateTime> MonthlyEndDate_Local { get; set; }
        public Nullable<bool> MonthlyNow { get; set; }
        public System.DateTime LastUpdateDate_UTC { get; set; }
        public int LastUpdateContactTVItemID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClimateDataValue> ClimateDataValues { get; set; }
        public virtual TVItem TVItem { get; set; }
    }
}
