//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleMapPNG
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabSheet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LabSheet()
        {
            this.LabSheetDetails = new HashSet<LabSheetDetail>();
        }
    
        public int LabSheetID { get; set; }
        public int OtherServerLabSheetID { get; set; }
        public int SamplingPlanID { get; set; }
        public string SamplingPlanName { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public int Day { get; set; }
        public int RunNumber { get; set; }
        public int SubsectorTVItemID { get; set; }
        public Nullable<int> MWQMRunTVItemID { get; set; }
        public int SamplingPlanType { get; set; }
        public int SampleType { get; set; }
        public int LabSheetType { get; set; }
        public int LabSheetStatus { get; set; }
        public string FileName { get; set; }
        public System.DateTime FileLastModifiedDate_Local { get; set; }
        public string FileContent { get; set; }
        public Nullable<int> AcceptedOrRejectedByContactTVItemID { get; set; }
        public Nullable<System.DateTime> AcceptedOrRejectedDateTime { get; set; }
        public string RejectReason { get; set; }
        public System.DateTime LastUpdateDate_UTC { get; set; }
        public int LastUpdateContactTVItemID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LabSheetDetail> LabSheetDetails { get; set; }
        public virtual TVItem TVItem { get; set; }
        public virtual TVItem TVItem1 { get; set; }
        public virtual SamplingPlan SamplingPlan { get; set; }
        public virtual TVItem TVItem2 { get; set; }
    }
}
