//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleMapPNG
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabSheetDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LabSheetDetail()
        {
            this.LabSheetTubeMPNDetails = new HashSet<LabSheetTubeMPNDetail>();
        }
    
        public int LabSheetDetailID { get; set; }
        public int LabSheetID { get; set; }
        public int SamplingPlanID { get; set; }
        public int SubsectorTVItemID { get; set; }
        public int Version { get; set; }
        public System.DateTime RunDate { get; set; }
        public string Tides { get; set; }
        public string SampleCrewInitials { get; set; }
        public Nullable<int> WaterBathCount { get; set; }
        public Nullable<System.DateTime> IncubationBath1StartTime { get; set; }
        public Nullable<System.DateTime> IncubationBath2StartTime { get; set; }
        public Nullable<System.DateTime> IncubationBath3StartTime { get; set; }
        public Nullable<System.DateTime> IncubationBath1EndTime { get; set; }
        public Nullable<System.DateTime> IncubationBath2EndTime { get; set; }
        public Nullable<System.DateTime> IncubationBath3EndTime { get; set; }
        public Nullable<int> IncubationBath1TimeCalculated_minutes { get; set; }
        public Nullable<int> IncubationBath2TimeCalculated_minutes { get; set; }
        public Nullable<int> IncubationBath3TimeCalculated_minutes { get; set; }
        public string WaterBath1 { get; set; }
        public string WaterBath2 { get; set; }
        public string WaterBath3 { get; set; }
        public Nullable<double> TCField1 { get; set; }
        public Nullable<double> TCLab1 { get; set; }
        public Nullable<double> TCField2 { get; set; }
        public Nullable<double> TCLab2 { get; set; }
        public Nullable<double> TCFirst { get; set; }
        public Nullable<double> TCAverage { get; set; }
        public string ControlLot { get; set; }
        public string Positive35 { get; set; }
        public string NonTarget35 { get; set; }
        public string Negative35 { get; set; }
        public string Bath1Positive44_5 { get; set; }
        public string Bath2Positive44_5 { get; set; }
        public string Bath3Positive44_5 { get; set; }
        public string Bath1NonTarget44_5 { get; set; }
        public string Bath2NonTarget44_5 { get; set; }
        public string Bath3NonTarget44_5 { get; set; }
        public string Bath1Negative44_5 { get; set; }
        public string Bath2Negative44_5 { get; set; }
        public string Bath3Negative44_5 { get; set; }
        public string Blank35 { get; set; }
        public string Bath1Blank44_5 { get; set; }
        public string Bath2Blank44_5 { get; set; }
        public string Bath3Blank44_5 { get; set; }
        public string Lot35 { get; set; }
        public string Lot44_5 { get; set; }
        public string Weather { get; set; }
        public string RunComment { get; set; }
        public string RunWeatherComment { get; set; }
        public string SampleBottleLotNumber { get; set; }
        public string SalinitiesReadBy { get; set; }
        public Nullable<System.DateTime> SalinitiesReadDate { get; set; }
        public string ResultsReadBy { get; set; }
        public Nullable<System.DateTime> ResultsReadDate { get; set; }
        public string ResultsRecordedBy { get; set; }
        public Nullable<System.DateTime> ResultsRecordedDate { get; set; }
        public Nullable<double> DailyDuplicateRLog { get; set; }
        public Nullable<double> DailyDuplicatePrecisionCriteria { get; set; }
        public Nullable<bool> DailyDuplicateAcceptable { get; set; }
        public Nullable<double> IntertechDuplicateRLog { get; set; }
        public Nullable<double> IntertechDuplicatePrecisionCriteria { get; set; }
        public Nullable<bool> IntertechDuplicateAcceptable { get; set; }
        public Nullable<bool> IntertechReadAcceptable { get; set; }
        public System.DateTime LastUpdateDate_UTC { get; set; }
        public int LastUpdateContactTVItemID { get; set; }
    
        public virtual LabSheet LabSheet { get; set; }
        public virtual SamplingPlan SamplingPlan { get; set; }
        public virtual TVItem TVItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LabSheetTubeMPNDetail> LabSheetTubeMPNDetails { get; set; }
    }
}
