//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleMapPNG
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabSheetTubeMPNDetail
    {
        public int LabSheetTubeMPNDetailID { get; set; }
        public int LabSheetDetailID { get; set; }
        public int Ordinal { get; set; }
        public int MWQMSiteTVItemID { get; set; }
        public Nullable<System.DateTime> SampleDateTime { get; set; }
        public Nullable<int> MPN { get; set; }
        public Nullable<int> Tube10 { get; set; }
        public Nullable<int> Tube1_0 { get; set; }
        public Nullable<int> Tube0_1 { get; set; }
        public Nullable<double> Salinity { get; set; }
        public Nullable<double> Temperature { get; set; }
        public string ProcessedBy { get; set; }
        public int SampleType { get; set; }
        public string SiteComment { get; set; }
        public System.DateTime LastUpdateDate_UTC { get; set; }
        public int LastUpdateContactTVItemID { get; set; }
    
        public virtual LabSheetDetail LabSheetDetail { get; set; }
        public virtual TVItem TVItem { get; set; }
    }
}
