//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleMapPNG
{
    using System;
    using System.Collections.Generic;
    
    public partial class MikeScenario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MikeScenario()
        {
            this.MikeScenarios1 = new HashSet<MikeScenario>();
        }
    
        public int MikeScenarioID { get; set; }
        public int MikeScenarioTVItemID { get; set; }
        public Nullable<int> ParentMikeScenarioID { get; set; }
        public int ScenarioStatus { get; set; }
        public string ErrorInfo { get; set; }
        public System.DateTime MikeScenarioStartDateTime_Local { get; set; }
        public System.DateTime MikeScenarioEndDateTime_Local { get; set; }
        public Nullable<System.DateTime> MikeScenarioStartExecutionDateTime_Local { get; set; }
        public Nullable<double> MikeScenarioExecutionTime_min { get; set; }
        public double WindSpeed_km_h { get; set; }
        public double WindDirection_deg { get; set; }
        public double DecayFactor_per_day { get; set; }
        public bool DecayIsConstant { get; set; }
        public double DecayFactorAmplitude { get; set; }
        public int ResultFrequency_min { get; set; }
        public double AmbientTemperature_C { get; set; }
        public double AmbientSalinity_PSU { get; set; }
        public double ManningNumber { get; set; }
        public Nullable<int> NumberOfElements { get; set; }
        public Nullable<int> NumberOfTimeSteps { get; set; }
        public Nullable<int> NumberOfSigmaLayers { get; set; }
        public Nullable<int> NumberOfZLayers { get; set; }
        public Nullable<int> NumberOfHydroOutputParameters { get; set; }
        public Nullable<int> NumberOfTransOutputParameters { get; set; }
        public Nullable<long> EstimatedHydroFileSize { get; set; }
        public Nullable<long> EstimatedTransFileSize { get; set; }
        public System.DateTime LastUpdateDate_UTC { get; set; }
        public int LastUpdateContactTVItemID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MikeScenario> MikeScenarios1 { get; set; }
        public virtual MikeScenario MikeScenario1 { get; set; }
        public virtual TVItem TVItem { get; set; }
    }
}
