//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleMapPNG
{
    using System;
    using System.Collections.Generic;
    
    public partial class MWQMRunLanguage
    {
        public int MWQMRunLanguageID { get; set; }
        public int MWQMRunID { get; set; }
        public int Language { get; set; }
        public string RunComment { get; set; }
        public int TranslationStatusRunComment { get; set; }
        public string RunWeatherComment { get; set; }
        public int TranslationStatusRunWeatherComment { get; set; }
        public System.DateTime LastUpdateDate_UTC { get; set; }
        public int LastUpdateContactTVItemID { get; set; }
    
        public virtual MWQMRun MWQMRun { get; set; }
    }
}
