//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleMapPNG
{
    using System;
    using System.Collections.Generic;
    
    public partial class MWQMAnalysisReportParameter
    {
        public int MWQMAnalysisReportParameterID { get; set; }
        public int SubsectorTVItemID { get; set; }
        public string AnalysisName { get; set; }
        public Nullable<int> AnalysisReportYear { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int AnalysisCalculationType { get; set; }
        public int NumberOfRuns { get; set; }
        public bool FullYear { get; set; }
        public double SalinityHighlightDeviationFromAverage { get; set; }
        public int ShortRangeNumberOfDays { get; set; }
        public int MidRangeNumberOfDays { get; set; }
        public int DryLimit24h { get; set; }
        public int DryLimit48h { get; set; }
        public int DryLimit72h { get; set; }
        public int DryLimit96h { get; set; }
        public int WetLimit24h { get; set; }
        public int WetLimit48h { get; set; }
        public int WetLimit72h { get; set; }
        public int WetLimit96h { get; set; }
        public string RunsToOmit { get; set; }
        public string ShowDataTypes { get; set; }
        public Nullable<int> ExcelTVFileTVItemID { get; set; }
        public int Command { get; set; }
        public System.DateTime LastUpdateDate_UTC { get; set; }
        public int LastUpdateContactTVItemID { get; set; }
    
        public virtual TVItem TVItem { get; set; }
        public virtual TVItem TVItem1 { get; set; }
    }
}
