//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleMapPNG
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportTypeLanguage
    {
        public int ReportTypeLanguageID { get; set; }
        public int ReportTypeID { get; set; }
        public int Language { get; set; }
        public string Name { get; set; }
        public int TranslationStatusName { get; set; }
        public string Description { get; set; }
        public int TranslationStatusDescription { get; set; }
        public string StartOfFileName { get; set; }
        public int TranslationStatusStartOfFileName { get; set; }
        public System.DateTime LastUpdateDate_UTC { get; set; }
        public int LastUpdateContactTVItemID { get; set; }
    
        public virtual ReportType ReportType { get; set; }
    }
}
