//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleMapPNG
{
    using System;
    using System.Collections.Generic;
    
    public partial class TideDataValue
    {
        public int TideDataValueID { get; set; }
        public int TideSiteTVItemID { get; set; }
        public System.DateTime DateTime_Local { get; set; }
        public bool Keep { get; set; }
        public int TideDataType { get; set; }
        public int StorageDataType { get; set; }
        public double Depth_m { get; set; }
        public double UVelocity_m_s { get; set; }
        public double VVelocity_m_s { get; set; }
        public Nullable<int> TideStart { get; set; }
        public Nullable<int> TideEnd { get; set; }
        public System.DateTime LastUpdateDate_UTC { get; set; }
        public int LastUpdateContactTVItemID { get; set; }
    
        public virtual TVItem TVItem { get; set; }
    }
}
