//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleMapPNG
{
    using System;
    using System.Collections.Generic;
    
    public partial class TVItemLink
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TVItemLink()
        {
            this.TVItemLinks1 = new HashSet<TVItemLink>();
        }
    
        public int TVItemLinkID { get; set; }
        public int FromTVItemID { get; set; }
        public int ToTVItemID { get; set; }
        public int FromTVType { get; set; }
        public int ToTVType { get; set; }
        public Nullable<System.DateTime> StartDateTime_Local { get; set; }
        public Nullable<System.DateTime> EndDateTime_Local { get; set; }
        public int Ordinal { get; set; }
        public int TVLevel { get; set; }
        public string TVPath { get; set; }
        public Nullable<int> ParentTVItemLinkID { get; set; }
        public System.DateTime LastUpdateDate_UTC { get; set; }
        public int LastUpdateContactTVItemID { get; set; }
    
        public virtual TVItem TVItem { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TVItemLink> TVItemLinks1 { get; set; }
        public virtual TVItemLink TVItemLink1 { get; set; }
        public virtual TVItem TVItem1 { get; set; }
    }
}
