//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoogleMapPNG
{
    using System;
    using System.Collections.Generic;
    
    public partial class UseOfSite
    {
        public int UseOfSiteID { get; set; }
        public int SiteTVItemID { get; set; }
        public int SubsectorTVItemID { get; set; }
        public int SiteType { get; set; }
        public int Ordinal { get; set; }
        public int StartYear { get; set; }
        public Nullable<int> EndYear { get; set; }
        public Nullable<bool> UseWeight { get; set; }
        public Nullable<double> Weight_perc { get; set; }
        public Nullable<bool> UseEquation { get; set; }
        public Nullable<double> Param1 { get; set; }
        public Nullable<double> Param2 { get; set; }
        public Nullable<double> Param3 { get; set; }
        public Nullable<double> Param4 { get; set; }
        public System.DateTime LastUpdateDate_UTC { get; set; }
        public int LastUpdateContactTVItemID { get; set; }
    
        public virtual TVItem TVItem { get; set; }
        public virtual TVItem TVItem1 { get; set; }
    }
}
